server:
  port: 8082

spring:
  application:
    name: user-consumer
  datasource:
    url: jdbc:mysql://localhost:3306/test-user?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alibaba:
      seata:
        #seata事务组名称，对应file.conf文件中vgroup_mapping.user-consumer-tx-service-group
        tx-service-group: user-consumer-tx-service-group

dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: user-provider
  consumer:
    check: false
